### PR TITLE
Configurable npm prefix option for local npm path

### LINKED ISSUE #35: wrong local path to find npm bin
Currently needed npm pacakges are searched in wrong local directory. Missing assets prefix (it is default standard setup in phoenix).

This is crude soluton. It might break it for others:
```diff
+local_bin = npm_bin(npm_path, ["--prefix", "./assets"])
-local_bin = npm_bin(npm_path)
global_bin = npm_bin(npm_path, ["--global"])
```

Probably better solution would be to provide some configuration options.

### PR DESCRIPTION
**Pull request by revati**
Closes #35

### CODE REVIEW

File: lib/vega_lite/export.ex [hunk 1]
```diff
@@ -39,13 +39,13 @@ defmodule VegaLite.Export do
           to_html(vl)
 
         :png ->
-          to_png(vl)
+          to_png(vl, Keyword.delete(opts, :format))
```
Comment (josevalim) [inline lib/vega_lite/export.ex:42]: Instead of deleting it here, you can change get_lazy a couple lines above to do this:

```
{format, opts} =
  Keyword.pop_lazy(...
```

:)

**Comment by josevalim** [comment]
There is now one warning on `defp npm_bin(npm_path, args \\ []) do`. Can you please remove the default arguments? Then we are good to go :)

File: lib/vega_lite/export.ex [hunk 2]
```diff
@@ -110,56 +112,77 @@ defmodule VegaLite.Export do
...
     npm_path = System.find_executable("npm")
 
     unless npm_path do
       raise RuntimeError,
             "#{fn_name} requires Node.js and npm to be installed and available in PATH"
     end
 
-    local_bin = npm_bin(npm_path)
+    local_bin_args =
+      case Keyword.get(opts, :local_npm_prefix) do
```
Comment (jonatanklosko) [inline lib/vega_lite/export.ex:180]:
```suggestion
      case opts[:local_npm_prefix] do
```

File: lib/vega_lite/export.ex [hunk 3]
```diff
@@ -110,56 +112,77 @@ defmodule VegaLite.Export do
   its binary content.
 
   Relies on the `npm` packages mentioned above.
+
+  ## Options
+
+  * `:local_npm_prefix` - used for `:png`, `:svg`, `:pdf` formats to help locate local npm directory.
+    For example in Phoenix projects you need to pass `local_npm_prefix: "assets"`.
   """
   @spec to_png(VegaLite.t()) :: binary()
```
Comment (jonatanklosko) [inline lib/vega_lite/export.ex:121]:
```suggestion
  @spec to_png(VegaLite.t(), keyword()) :: binary()
```

File: lib/vega_lite/export.ex [hunk 4]
```diff
@@ -110,56 +112,77 @@ defmodule VegaLite.Export do
...
   its binary content.
 
   Relies on the `npm` packages mentioned above.
+
+  ## Options
+
+  * `:local_npm_prefix` - used for `:png`, `:svg`, `:pdf` formats to help locate local npm directory.
+    For example in Phoenix projects you need to pass `local_npm_prefix: "assets"`.
   """
   @spec to_svg(VegaLite.t()) :: binary()
```
Comment (jonatanklosko) [inline lib/vega_lite/export.ex:137]:
```suggestion
  @spec to_svg(VegaLite.t(), keyword()) :: binary()
```

File: lib/vega_lite/export.ex [hunk 5]
```diff
@@ -110,56 +112,77 @@ defmodule VegaLite.Export do
...
   binary content.
 
   Relies on the `npm` packages mentioned above.
+
+  ## Options
+
+  * `:local_npm_prefix` - used for `:png`, `:svg`, `:pdf` formats to help locate local npm directory.
+    For example in Phoenix projects you need to pass `local_npm_prefix: "assets"`.
   """
   @spec to_pdf(VegaLite.t()) :: binary()
```
Comment (jonatanklosko) [inline lib/vega_lite/export.ex:153]:
```suggestion
  @spec to_pdf(VegaLite.t(), keyword()) :: binary()
```

File: lib/vega_lite/export.ex [hunk 6]
```diff
@@ -22,11 +22,13 @@ defmodule VegaLite.Export do
     * `:format` - the format to export the graphic as,
       must be either of: `:json`, `:html`, `:png`, `:svg`, `:pdf`.
       By default the format is inferred from the file extension.
+    * `:local_npm_prefix` - used for `:png`, `:svg`, `:pdf` formats to help locate local npm directory.
+      For example in Phoenix projects you need to pass `local_npm_prefix: "assets"`.
```
Comment (jonatanklosko) [inline lib/vega_lite/export.ex:26]:
```suggestion

    * `:local_npm_prefix` - a relative path pointing to a local npm project directory
      where the necessary npm packages are installed. For instance, in Phoenix projects
      you may want to pass `local_npm_prefix: "assets"`. By default the npm packages
      are searched for in the current directory and globally.
```

File: lib/vega_lite/export.ex [hunk 7]
```diff
@@ -110,56 +112,77 @@ defmodule VegaLite.Export do
   its binary content.
 
   Relies on the `npm` packages mentioned above.
+
+  ## Options
+
+  * `:local_npm_prefix` - used for `:png`, `:svg`, `:pdf` formats to help locate local npm directory.
+    For example in Phoenix projects you need to pass `local_npm_prefix: "assets"`.
```
Comment (jonatanklosko) [inline lib/vega_lite/export.ex:119]:
```suggestion
    * `:local_npm_prefix` - a relative path pointing to a local npm project directory
      where the necessary npm packages are installed. For instance, in Phoenix projects
      you may want to pass `local_npm_prefix: "assets"`. By default the npm packages
      are searched for in the current directory and globally.
```

File: lib/vega_lite/export.ex [hunk 8]
```diff
@@ -110,56 +112,77 @@ defmodule VegaLite.Export do
...
   @doc """
   Renders the given graphic as an SVG image and returns
   its binary content.
 
   Relies on the `npm` packages mentioned above.
+
+  ## Options
+
+  * `:local_npm_prefix` - used for `:png`, `:svg`, `:pdf` formats to help locate local npm directory.
+    For example in Phoenix projects you need to pass `local_npm_prefix: "assets"`.
```
Comment (jonatanklosko) [inline lib/vega_lite/export.ex:135]:
```suggestion
    * `:local_npm_prefix` - a relative path pointing to a local npm project directory
      where the necessary npm packages are installed. For instance, in Phoenix projects
      you may want to pass `local_npm_prefix: "assets"`. By default the npm packages
      are searched for in the current directory and globally.
```

File: lib/vega_lite/export.ex [hunk 9]
```diff
@@ -110,56 +112,77 @@ defmodule VegaLite.Export do
...
   @doc """
   Renders the given graphic into a PDF and returns its
   binary content.
 
   Relies on the `npm` packages mentioned above.
+
+  ## Options
+
+  * `:local_npm_prefix` - used for `:png`, `:svg`, `:pdf` formats to help locate local npm directory.
+    For example in Phoenix projects you need to pass `local_npm_prefix: "assets"`.
```
Comment (jonatanklosko) [inline lib/vega_lite/export.ex:151]:
```suggestion
    * `:local_npm_prefix` - a relative path pointing to a local npm project directory
      where the necessary npm packages are installed. For instance, in Phoenix projects
      you may want to pass `local_npm_prefix: "assets"`. By default the npm packages
      are searched for in the current directory and globally.
```

**Review by jonatanklosko — COMMENTED** [review]
Thanks!

**Comment by revati** [comment]
Thanks @josevalim and @jonatanklosko for tips and suggestions. Have updated code accordingly.

**Comment by josevalim** [comment]
@revati I think the docs changes are missing. Then it should be good! :)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
